### PR TITLE
DVP: Mark generated objects as PIC

### PR DESCRIPTION
**Pull request by F0bes**
Currently when you try to link objects generated by dvp-as you'll get a warning like this:
`/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/13.2.0/../../../../mips64r5900el-ps2-elf/bin/ld: vu1_esin.o: warning: linking abicalls files with non-abicalls files`

I could've patched the linker to ignore the mismatch, or make dvp-as add the require elf header flag (EF_MIPS_CPIC). I did the latter, and that's what this PR is. You can also pass -no-abicalls to disable this.

### CODE REVIEW

**Comment by rickgaiser** [comment]
Are we really 'linking' dvp object files with ee object files? Or is this more like the situation we have with IRX files, where we just want to embed a binary blob into the ee elf. And only really link 2 symbols: size and datablob.

See also this related PR:
https://github.com/ps2dev/ps2sdk/pull/513

And the issues that PR links to.

**Comment by F0bes** [comment]
Yes, you link the dvp object(s) to the EE elf. There is a special .vudata segment in the elf.
See this example: https://github.com/F0bes/PS2DVD/blob/master/ps2dvd.c#L14

I suppose this flag should be set for bin2s and bin2o files as well.

Unrelated to the PR, but I don't like using bin2c for large objects due to the substantial increase in complication times. I think bin2o can be better suited for something like that.
Edit: Unless I'm mistaken and it takes the same amount of time 😅

**Comment by rickgaiser** [comment]
The example shows it nicely. Every symbol defined in your .vsm can be linked to from ee code. So it really is linking and not just using the data blob. Then this PR lgtm.

**Comment by uyjulian** [comment]
Lgtm

**Pull request merged**
